services:
  syncify-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/.venv
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/syncify-db
    env_file:
      - backend/.env
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: "redis:alpine"
    expose:
      - "6379"
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8081:8001"
    depends_on:
      - redis
    volumes:
      - redisinsight:/db

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - backend/.env

volumes:
  postgres_data:
  redisinsight: