"""initial migration

Revision ID: 469f5ac4bc8e
Revises: 
Create Date: 2024-11-17 17:24:22.602444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469f5ac4bc8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('spotify_id', sa.String, nullable=True),
    sa.Column('country', sa.String, nullable=True),
    sa.Column('display_name', sa.String, nullable=False),
    sa.Column('email', sa.String, nullable=False),
    sa.Column('avatar', sa.String, nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('currently_playing', sa.String, nullable=True),
    sa.Column('id', sa.String, nullable=False),
    sa.Column('password_hash', sa.String, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friends_association',
    sa.Column('user_id', sa.String, nullable=False),
    sa.Column('friend_id', sa.String, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.String, nullable=False),
    sa.Column('user_id', sa.String, nullable=False),
    sa.Column('token', sa.String, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_user_id'), 'tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_user_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('friends_association')
    op.drop_table('users')
    # ### end Alembic commands ###
